language: python
dist: xenial
python:
  - 3.7
install:
  - pip install -e ".[dev]"
script:
  - py.test --cov . --cov-report xml:coverage.xml

env:
  global:
    - CC_TEST_REPORTER_ID=16bcfb0958d99f11456f8d80aeb5800d567724471e151fe6e74a4b329b45dcb6

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
